Repository meilisearch/specifications, pull requests merged in 2021-07, with the labels that each got.

#54 Add CI tests to check yaml formating
  .github/workflows/tests.yml
  .yamllint.yml
Labels: Not A Spec

#53 Add v0.21.0 OpenApi Specification
  open-api.yaml
Labels: v0.21

#57 Change the /version response
  open-api.yaml
Labels: Implemented, v0.21
