Repository meilisearch/specifications, pull requests merged in 2021-11, with the labels that each got.

#84 Rework Analytics Stack
  text/0034-telemetry-policies.md
Labels: Ready For Review, Q4:2021, v0.24

#91 Fix documentation of search `sort` query param
  open-api.yaml
Labels: OpenAPI

#88 Release v0.24.0
  .github/workflows/bump.yml
  open-api.yaml
  text/0034-telemetry-policies.md
  text/0061-error-format-and-definitions.md
  text/0077-words-position-limit.md
Labels: Not A Spec, OpenAPI, v0.24

#90 Add `details` payload by task type and index deletion behavior on task retrieval
  text/0060-refashion-updates-apis.md
Labels: Patch

#92 Update telemetry policies for new task endpoints
  text/0034-telemetry-policies.md
Labels: Telemetry

#93 Patch Task specification for `details` part.
  text/0060-refashion-updates-apis.md
Labels: Patch

#94 Add technical detail about the first Launched event and the segment identify call
  text/0034-telemetry-policies.md
Labels: Ready For Review, Patch

#95 Replace q.avg_terms_number by q.max_terms_number in telemetry spec
  text/0034-telemetry-policies.md
Labels: Q4:2021, Patch, v0.25, Telemetry
