Repository meilisearch/specifications, pull requests merged in 2021-06, with the labels that each got.

#42 Paginated Search
  text/0042-paginated-search.md
Labels: Ready For Review

#29 Indexing NDJSONs
  text/0029-indexing-ndjson.md
Labels: Q3:2021, Ready For Review

#28 Indexing CSVs
  text/0028-indexing-csv.md
Labels: Q3:2021, Ready For Review

#43 Phrase Query
  text/0043-phrase-query.md
Labels: Q2:2021, Ready For Review, v0.21

#48 Rename MAX_MDB_SIZE env var and --max-mdb-size option flag
  text/0048-rename-max-mdb-size-var.md
Labels: Q2:2021, Ready For Review, v0.21

#36 Exactness Criterion
  text/0036-exactness-criterion.md
Labels: Q2:2021, Ready For Review, v0.21

#51 Add tracking issue to phrase search spec
  text/0043-phrase-query.md
Labels: Not A Spec

#39 _formatted Field Behavior
  text/0039-_formatted-field-behavior.md
Labels: Q2:2021, Ready For Review, v0.21

#34 Analytics Policy
  text/0034-telemetry-policies.md
Labels: Q2:2021, Ready For Review, v0.21

#33 Logging
  text/0033-logging.md
Labels: Q2:2021, Ready For Review, v0.21

#47 Reset Stop-Words and Synonyms Settings With A Null Value
  text/0047-reset-stop-words-synonyms-settings-with-null.md
Labels: Q2:2021, Ready For Review, v0.21
