Repository meilisearch/specifications, pull requests merged in 2022-11, with the labels that each got.

#200 Update Specification Workflow
  README.md
Labels: Not A Spec

#178 Compression Headers
  text/0178-compression-headers.md
Labels: Ready For Review, Implemented, Q4:2022, v0.30

#179 Keys API - Indicate to users that a master key must be set at Meilisearch launch to use that feature
  text/0061-error-format-and-definitions.md
  text/0085-api-keys.md
Labels: Implemented, Q4:2022, v0.30, ⚠️ Breaking

#181 Keys API - Add a variant message when an index uid format is invalid for the indexes field.
  text/0061-error-format-and-definitions.md
Labels: Implemented, Q4:2022, v0.30

#184 Instance Options - `localhost:7700` instead of `127.0.0.1:7700`
  text/0119-instance-options.md
Labels: Implemented, Q4:2022, v0.30

#185 Configuration File Support
  text/0034-telemetry-policies.md
  text/0119-instance-options.md
  text/0185-configuration-file.md
Labels: Implemented, Q4:2022, Telemetry, v0.30

#187 Instance Options - Precise that `--max-index-size` is for an index and not all indexes.
  text/0119-instance-options.md
Labels: Ready For Review, Q4:2022, Catch-Up, v0.30

#192 Swap Indexes API
  open-api.yaml
  text/0034-telemetry-policies.md
  text/0060-tasks-api.md
  text/0061-error-format-and-definitions.md
  text/0085-api-keys.md
  text/0191-swap-indexes-api.md
Labels: Ready For Review, OpenAPI, Q4:2022, Telemetry, v0.30

#194 Tasks API - Add task priority order section
  text/0060-tasks-api.md
Labels: Ready For Review, Q4:2022, v0.30

#196 Search API - Page Selection Component
  open-api.yaml
  text/0034-telemetry-policies.md
  text/0118-search-api.md
Labels: Ready For Review, OpenAPI, Q4:2022, Telemetry, v0.30

#198 Tasks API - Add task deletion capability
  open-api.yaml
  text/0034-telemetry-policies.md
  text/0060-tasks-api.md
  text/0061-error-format-and-definitions.md
  text/0085-api-keys.md
Labels: Implemented, OpenAPI, Q4:2022, Telemetry, v0.30

#195 Tasks API - Add task cancelation capability
  open-api.yaml
  text/0034-telemetry-policies.md
  text/0060-tasks-api.md
  text/0061-error-format-and-definitions.md
  text/0085-api-keys.md
Labels: Ready For Review, OpenAPI, Q4:2022, Telemetry, v0.30, ⚠️ Breaking

#199 Dumps - Add dumpv6 to the support table
  text/0105-dumps-api.md
Labels: Implemented, Q4:2022, v0.30

#176 Release v0.30.0
  open-api.yaml
  text/0028-indexing-csv.md
  text/0029-indexing-ndjson.md
  text/0034-telemetry-policies.md
  text/0060-tasks-api.md
  text/0061-error-format-and-definitions.md
  text/0085-api-keys.md
  text/0105-dumps-api.md
  text/0117-typo-tolerance-setting-api.md
  text/0118-search-api.md
  text/0119-instance-options.md
  text/0123-settings-api.md
  text/0135-indexing-json.md
  text/0178-compression-headers.md
  text/0185-configuration-file.md
  text/0191-swap-indexes-api.md
  text/157-faceting-setting-api.md
  text/157-pagination-setting-api.md
Labels: ⚠️ Breaking, Release Tracker
