Repository meilisearch/specifications, pull requests merged in 2022-10, with the labels that each got.

#159 Tokenizer - Update specification to fit Charabia implementation
  text/0001-script-based-tokenizer.md
Labels: Ready For Review, Catch-Up, v0.29

#161 Geosearch - Add error variants for `invalid_geo_field` error
  text/0061-error-format-and-definitions.md
Labels: Ready For Review, v0.29

#162 Auto-batching - Enable feature by default and remove unwanted options
  open-api.yaml
  text/0034-telemetry-policies.md
  text/0060-tasks-api.md
  text/0096-auto-batching.md
  text/0119-instance-options.md
Labels: Ready For Review, OpenAPI, Q3:2022, Telemetry, v0.29

#163 Search API — Filters - Introduce IN and EXISTS and describe filter capabilities in more precisely
  text/0118-search-api.md
Labels: Ready For Review, v0.29

#169 Telemetry - Add `Stats Seen` event
  text/0034-telemetry-policies.md
Labels: Implemented, Q3:2022, Telemetry, v0.29

#170 Misc — Add examples components for each summarized task type
  open-api.yaml
Labels: Not A Spec, OpenAPI, Q3:2022, Catch-Up, v0.29

#171 Version API — Catch up
  text/0171-version-api.md
Labels: Ready For Review, Implemented, Q3:2022, Catch-Up, v0.29

#172 Health API — Catch up
  text/0172-health-api.md
Labels: Ready For Review, Implemented, Q3:2022, Catch-Up, v0.29

#173 Search API — Add `matchingStrategy` parameter with `last` / `all` strategies
  open-api.yaml
  text/0034-telemetry-policies.md
  text/0118-search-api.md
Labels: OpenAPI, Telemetry, v0.29

#167 Documents API — Indexing json
  text/0124-documents-api.md
  text/0135-indexing-json.md
Labels: Implemented, Catch-Up, v0.29

#160 Release v0.29.0
  open-api.yaml
  text/0001-script-based-tokenizer.md
  text/0034-telemetry-policies.md
  text/0060-tasks-api.md
  text/0061-error-format-and-definitions.md
  text/0096-auto-batching.md
  text/0118-search-api.md
  text/0119-instance-options.md
  text/0124-documents-api.md
  text/0132-indexes-api.md
  text/0135-indexing-json.md
  text/0136-documents-soft-deletion.md
  text/0171-version-api.md
  text/0172-health-api.md
Labels: Not A Spec

#191 GitHub Actions - Trigger OpenAPI Diff on `release-v*` branches
  .github/workflows/bump.yml
Labels: Not A Spec
