Repository meilisearch/specifications, pull requests merged in 2022-03, with the labels that each got.

#118 Search API
  text/0118-search-api.md
Labels: Ready For Review

#110 Handle empty cell as `null` value for CSV format
  text/0028-indexing-csv.md
Labels: Implemented, Patch, Q1:2022, v0.26

#105 Dumps
  text/0105-dumps-api.md
Labels: Ready For Review, Q1:2022, v0.26

#98 Accepts 0 documents payload on `POST`/`PUT`- `/documents`
  text/0061-error-format-and-definitions.md
Labels: Ready To Be Implemented, Patch, Q1:2022, v0.26

#114 Keys API - Update the error message for `expiresAt`
  open-api.yaml
  text/0060-tasks-api.md
  text/0061-error-format-and-definitions.md
  text/0085-api-keys.md
Labels: Ready For Review, Patch, v0.26

#122 Dump support
  text/0105-dumps-api.md
Labels: Ready For Review, Patch, Catch-Up

#89 Tenant Token
  text/0089-tenant-tokens.md
Labels: Ready For Review, Q1:2022, v0.26, P1

#96 Auto-Batching
  open-api.yaml
  text/0034-telemetry-policies.md
  text/0060-tasks-api.md
  text/0096-auto-batching.md
Labels: Ready For Review, Q1:2022, v0.26, Experimental, P1

#126 Release v0.26.0
  open-api.yaml
  text/0028-indexing-csv.md
  text/0034-telemetry-policies.md
  text/0060-tasks-api.md
  text/0061-error-format-and-definitions.md
  text/0085-api-keys.md
  text/0089-tenant-tokens.md
  text/0096-auto-batching.md
  text/0105-dumps-api.md
  text/0118-search-api.md
Labels: Not A Spec, OpenAPI, P1

#123 Settings API - v0.26.0 state
  text/0118-search-api.md
  text/0123-displayed-attributes-setting-api.md
  text/0123-distinct-attribute-setting-api.md
  text/0123-filterable-attributes-setting-api.md
  text/0123-ranking-rules-setting-api.md
  text/0123-searchable-attributes-setting-api.md
  text/0123-settings-api.md
  text/0123-sortable-attributes-setting-api.md
  text/0123-stop-words-setting-api.md
  text/0123-synonyms-setting-api.md
Labels: Ready For Review, Implemented, Catch-Up

#127 Update spec template according to our current usage
  text/0000-specification-template.md
Labels: Not A Spec

#133 Documents API
  text/0124-documents-api.md
Labels: Implemented, Catch-Up

#134 Stats API
  text/0134-stats-api.md
Labels: Implemented, Catch-Up

#125 Errors - Add variant for `invalid_filter`/`invalid_sort` when related settings are empty
  text/0061-error-format-and-definitions.md
Labels: Ready For Review, Patch, Q2:2022, v0.27
