Repository meilisearch/specifications, pull requests merged in 2022-07, with the labels that each got.

#115 Tasks API - Seek/Keyset based pagination
  open-api.yaml
  text/0060-tasks-api.md
Labels: Ready For Review, OpenAPI, Q3:2022, v0.28

#116 Tasks API - Filter tasks list by `type`/`status`/`indexUid`
  open-api.yaml
  text/0034-telemetry-policies.md
  text/0060-tasks-api.md
  text/0061-error-format-and-definitions.md
Labels: Ready For Review, OpenAPI, Q3:2022, Telemetry, v0.28

#139 Dumps API - Make dump creation an asynchronous task
  open-api.yaml
  text/0060-tasks-api.md
  text/0061-error-format-and-definitions.md
  text/0085-api-keys.md
  text/0105-dumps-api.md
Labels: Ready For Review, OpenAPI, Q3:2022, v0.28

#138 API Guideline - Return list of API resources under a `results` array
  open-api.yaml
  text/0085-api-keys.md
  text/0124-documents-api.md
  text/0132-indexes-api.md
Labels: Ready For Review, Q3:2022, v0.28

#143 Documents API - `displayedAttributes` should not impact the documents API / Rename `attributesToRetrieve` to `fields`
  open-api.yaml
  text/0124-documents-api.md
Labels: Ready For Review, OpenAPI, Q3:2022, v0.28

#148 API Keys - Determinist API Keys + Security changes
  open-api.yaml
  text/0061-error-format-and-definitions.md
  text/0085-api-keys.md
  text/0089-tenant-tokens.md
Labels: Ready For Review, OpenAPI, Q3:2022, v0.28

#149 Geosearch - Enhance lat/lng format error messages
  text/0059-geo-search.md
  text/0061-error-format-and-definitions.md
Labels: Patch, v0.28

#150 Telemetry - Replace `x-meilisearch-client` query parameter by `X-Meilisearch-Client` header
  text/0034-telemetry-policies.md
Labels: Ready For Review, Q3:2022, Telemetry, v0.28

#154 Misc - Update `invalid_ranking_rule` error message
  text/0059-geo-search.md
  text/0061-error-format-and-definitions.md
Labels: Ready For Review, Q3:2022, v0.28

#156 Misc — Update dump versions compatibility table
  text/0105-dumps-api.md
Labels: Not A Spec, Q3:2022, v0.28

#157 Settings API - Customize the hard limits for `pagination` and `faceting`
  open-api.yaml
  text/0034-telemetry-policies.md
  text/0123-settings-api.md
  text/157-faceting-setting-api.md
  text/157-pagination-setting-api.md
Labels: Ready For Review, OpenAPI, Q3:2022, Telemetry, v0.28
