Repository meilisearch/specifications, pull requests merged in 2023-02, with the labels that each got.

#203 Simplify dump version section since v1.0 can import all dumps
  text/0105-dumps-api.md
Labels: Implemented, v1.0.0, Q1:2023

#204 Rename dump command from `--dumps-dir` to `--dump-dir`
  open-api.yaml
  text/0034-telemetry-policies.md
  text/0105-dumps-api.md
  text/0119-instance-options.md
Labels: Implemented, OpenAPI, Patch, Telemetry, v1.0.0, ⚠️ Breaking, Q1:2023

#206 Update the specification of soft-deleted documents
  text/0136-documents-soft-deletion.md
Labels: Implemented, v1.0.0, Q1:2023

#207 Remove `--max-index-size` and `--max-task-db-size`
  text/0034-telemetry-policies.md
  text/0060-tasks-api.md
  text/0119-instance-options.md
Labels: Implemented, Telemetry, v1.0.0, ⚠️ Breaking, Q1:2023

#208 Robustify Primary Key Inference - Update related errors
  text/0061-error-format-and-definitions.md
Labels: Implemented, v1.0.0, ⚠️ Breaking, Q1:2023

#209 Reject master keys shorter than 16 bytes in `production`
  text/0085-api-keys.md
  text/0119-instance-options.md
Labels: Ready For Review, Implemented, v1.0.0, ⚠️ Breaking, Q1:2023

#212 Errors handling enhancement
  text/0059-geo-search.md
  text/0060-tasks-api.md
  text/0061-error-format-and-definitions.md
  text/0085-api-keys.md
  text/0117-typo-tolerance-setting-api.md
  text/0118-search-api.md
  text/0123-displayed-attributes-setting-api.md
  text/0123-distinct-attribute-setting-api.md
  text/0123-filterable-attributes-setting-api.md
  text/0123-ranking-rules-setting-api.md
  text/0123-searchable-attributes-setting-api.md
  text/0123-settings-api.md
  text/0123-sortable-attributes-setting-api.md
  text/0123-stop-words-setting-api.md
  text/0123-synonyms-setting-api.md
  text/0124-documents-api.md
  text/0132-indexes-api.md
  text/0134-stats-api.md
  text/0191-swap-indexes-api.md
  text/157-faceting-setting-api.md
  text/157-pagination-setting-api.md
Labels: Ready For Review, v1.0.0, ⚠️ Breaking, Q1:2023

#213 Add error message when doing a migration
  text/0105-dumps-api.md
Labels: Implemented, Catch-Up, v1.0.0, Q1:2023

#214 Merge snapshot options
  text/0034-telemetry-policies.md
  text/0119-instance-options.md
Labels: Implemented, Telemetry, v1.0.0, ⚠️ Breaking, Q1:2023

#215 CLI - Remove `--disable-auto-batching` argument
  text/0034-telemetry-policies.md
  text/0096-auto-batching.md
  text/0119-instance-options.md
Labels: Implemented, Telemetry, v1.0.0, ⚠️ Breaking, Q1:2023

#218 Specify the effect of the `*` value when used in the task filters
  text/0060-tasks-api.md
Labels: Ready For Review, Catch-Up, v1.0.0, Q1:2023

#201 Release v1.0.0
  open-api.yaml
  text/0033-logging.md
  text/0034-telemetry-policies.md
  text/0059-geo-search.md
  text/0060-tasks-api.md
  text/0061-error-format-and-definitions.md
  text/0085-api-keys.md
  text/0096-auto-batching.md
  text/0105-dumps-api.md
  text/0117-typo-tolerance-setting-api.md
  text/0118-search-api.md
  text/0119-instance-options.md
  text/0123-displayed-attributes-setting-api.md
  text/0123-distinct-attribute-setting-api.md
  text/0123-filterable-attributes-setting-api.md
  text/0123-ranking-rules-setting-api.md
  text/0123-searchable-attributes-setting-api.md
  text/0123-settings-api.md
  text/0123-sortable-attributes-setting-api.md
  text/0123-stop-words-setting-api.md
  text/0123-synonyms-setting-api.md
  text/0124-documents-api.md
  text/0132-indexes-api.md
  text/0134-stats-api.md
  text/0136-documents-soft-deletion.md
  text/0191-swap-indexes-api.md
  text/157-faceting-setting-api.md
  text/157-pagination-setting-api.md
Labels: ⚠️ Breaking, Release Tracker
