Repository meilisearch/specifications, pull requests merged in 2023-06, with the labels that each got.

#228 CSV Content-Type — Add support for the boolean type in CSV
  text/0028-indexing-csv.md
Labels: Implemented, Q2:2023, v1.2.0

#232 Filter operators - `IS NULL` and `IS EMPTY` filter operators
  text/0118-search-api.md
Labels: Implemented, Q2:2023, v1.2.0

#236 Get and delete documents by filter
  open-api.yaml
  text/0034-telemetry-policies.md
  text/0060-tasks-api.md
  text/0061-error-format-and-definitions.md
  text/0085-api-keys.md
  text/0124-documents-api.md
Labels: Implemented, OpenAPI, Telemetry, Q2:2023, v1.2.0

#238 Auto deletion of tasks
  text/0060-tasks-api.md
Labels: Implemented, Q2:2023, v1.2.0

#240 Update sort Error message
  text/0055-sort.md
Labels: Implemented, Q2:2023, v1.2.0

#241 Update `payload_too_large` error `message`
  open-api.yaml
  text/0061-error-format-and-definitions.md
Labels: Implemented, Q2:2023, v1.2.0

#227 Release v1.2.0
  open-api.yaml
  text/0028-indexing-csv.md
  text/0030-asc-desc-criterion.md
  text/0034-telemetry-policies.md
  text/0036-exactness-criterion.md
  text/0055-sort.md
  text/0060-tasks-api.md
  text/0061-error-format-and-definitions.md
  text/0085-api-keys.md
  text/0118-search-api.md
  text/0119-instance-options.md
  text/0124-documents-api.md
Labels: Release Tracker
