Repository meilisearch/specifications, pull requests merged in 2023-04, with the labels that each got.

#174 Metrics API — Introduce a `/metrics` route for observability / monitoring purposes
  open-api.yaml
  text/0034-telemetry-policies.md
  text/0085-api-keys.md
  text/0119-instance-options.md
  text/0174-metrics-api.md
Labels: OpenAPI, Telemetry, Q1:2023, v1.1.0, 🧪 Experimental

#189 API Keys - Introduce `*` wildcard char at the last position to express access to multiple indexes starting with the same string
  open-api.yaml
  text/0061-error-format-and-definitions.md
  text/0085-api-keys.md
Labels: Implemented, OpenAPI, Q1:2023, v1.1.0

#221 Documents API — Support a csv delimiter customization
  open-api.yaml
  text/0028-indexing-csv.md
  text/0061-error-format-and-definitions.md
Labels: Implemented, OpenAPI, Q1:2023, v1.1.0

#222 Geosearch — Accept `null` for the `_geo` field
  text/0059-geo-search.md
Labels: Implemented, Q1:2023, v1.1.0

#226 Add small blurb about index count / max size
  text/0132-indexes-api.md
Labels: Implemented, Q1:2023, v1.1.0

#231 Specify the behaviour of the task queue once it is full
  text/0060-tasks-api.md
  text/0061-error-format-and-definitions.md
Labels: Ready For Review, Patch
