Repository meilisearch/specifications, pull requests merged in 2024-01, with the labels that each got.

#261 Add proximity precision setting
  text/0034-telemetry-policies.md
  text/0123-proximity-precision.md
  text/0123-settings-api.md
Labels: Ready For Review

#262 Task queue webhook
  text/0034-telemetry-policies.md
  text/0119-instance-options.md
  text/0262-task-queue-webhook.md
Labels: Ready For Review, Implemented, Telemetry

#260 Release v1.6.0
  open-api.yaml
  text/0034-telemetry-policies.md
  text/0119-instance-options.md
  text/0123-proximity-precision.md
  text/0123-settings-api.md
  text/0262-task-queue-webhook.md
Labels: Release Tracker
